/**
 * Generated file. Do not edit!
 **/
export enum EDocId {
	DEVICES = "DEVICES",
	IMPORTDEVICEHELP = "IMPORTDEVICEHELP",
	IMPORTWIZARD = "IMPORTWIZARD",
	NAMECOMPOSITIONS = "NAMECOMPOSITIONS",
	REMOTES = "REMOTES",
	RESOURCES = "RESOURCES",
	SAMPLES = "SAMPLES",
	TIMELINE = "TIMELINE",
	WELCOME = "WELCOME",
}
