version: "3.7"

services:
  repo-server-postgres:
    profiles: ["dev"]
    image: postgres:14
    env_file: env/dev.env
    ports:
      - 5432:5432
    volumes:
      - ./temp/postgres_data/:/var/lib/postgresql/data
