parameters: {}
environment:
  # The $ syntax is used to access variables defined in the app spec.
  #
  # For log forwarding to work in DO Functions, this environment variable needs to be in a special format.
  # Check the app spec for how it is defined, and/or consult the documentation:
  # https://docs.digitalocean.com/products/app-platform/how-to/manage-functions/#update-your-projectyml-file
  #
  # NOTE: This variable must be defined here, not below in the per-function environment variable block!
  LOG_DESTINATIONS: ${LOG_DESTINATIONS}
packages:
  - name: resources
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: downsample
        binary: false
        runtime: nodejs:18
        web: true
        parameters: {}
        environment:
          S3_ENDPOINT: "${S3_ENDPOINT}"
          S3_REGION: "${S3_REGION}"
          S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
          S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
          S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
          S3_PATH_PREFIX: "${S3_PATH_PREFIX}"

        annotations: {}
        limits:
          # Roughly 3MB/s, so this limits the files that can be processed to about 360MB
          timeout: 120e3
          memory: 384
