// @generated
// Generated by hendriksRouteGenerator.ts
/* eslint-disable import/order */
import type { ComponentType } from "react";

import type { IRouteGetDataFunction } from "./IRouteConfig";
import * as r0 from "./routes/_index";
import * as r1 from "./routes/login";
import * as r2 from "./routes/logout";
import * as r3 from "./routes/register";
import * as r4 from "./routes/repositories.$repositoryId._index";
import * as r5 from "./routes/repositories.$repositoryId.deviceDefinitions._index";
import * as r6 from "./routes/repositories.$repositoryId.devices.$deviceId.$deviceTimestamp";
import * as r7 from "./routes/repositories.$repositoryId.devices.$deviceId._index";
import * as r8 from "./routes/repositories.$repositoryId.devices.$deviceId.importer.$resourceId";
import * as r9 from "./routes/repositories.$repositoryId.devices._index";
import * as r10 from "./routes/repositories.$repositoryId.devices.flat";
import * as r11 from "./routes/repositories.$repositoryId.nameComposition._index";
import * as r12 from "./routes/repositories.$repositoryId.projects.$projectId";
import * as r13 from "./routes/repositories.$repositoryId.projects._index";
import * as r14 from "./routes/repositories.$repositoryId.resources.$resourceId";
import * as r15 from "./routes/repositories.$repositoryId.resources._index";
import * as r16 from "./routes/repositories.$repositoryId.samples.$sampleId";
import * as r17 from "./routes/repositories.$repositoryId.samples._index";
import * as r18 from "./routes/repositories.$repositoryId";
import * as r19 from "./routes/repositories.$repositoryId.users.$userId";
import * as r20 from "./routes/repositories._index";
import * as r21 from "./routes/repositories.settings";
import * as r22 from "./routes/repositories";

const route: {
	redirect?: string;
	getData?: IRouteGetDataFunction;
	default?: ComponentType<any>;
}[] = [
	r0,
	r1,
	r2,
	r3,
	r4,
	r5,
	r6,
	r7,
	r8,
	r9,
	r10,
	r11,
	r12,
	r13,
	r14,
	r15,
	r16,
	r17,
	r18,
	r19,
	r20,
	r21,
	r22,
];

export const routeConfig = {
	"/": { redirect: route[0].redirect, getData: route[0].getData, Component: route[0].default },
	"/login": { redirect: route[1].redirect, getData: route[1].getData, Component: route[1].default },
	"/logout": {
		redirect: route[2].redirect,
		getData: route[2].getData,
		Component: route[2].default,
	},
	"/register": {
		redirect: route[3].redirect,
		getData: route[3].getData,
		Component: route[3].default,
	},
	"/repositories/:repositoryId/": {
		redirect: route[4].redirect,
		getData: route[4].getData,
		Component: route[4].default,
	},
	"/repositories/:repositoryId/deviceDefinitions/": {
		redirect: route[5].redirect,
		getData: route[5].getData,
		Component: route[5].default,
	},
	"/repositories/:repositoryId/devices/:deviceId/:deviceTimestamp": {
		redirect: route[6].redirect,
		getData: route[6].getData,
		Component: route[6].default,
	},
	"/repositories/:repositoryId/devices/:deviceId/": {
		redirect: route[7].redirect,
		getData: route[7].getData,
		Component: route[7].default,
	},
	"/repositories/:repositoryId/devices/:deviceId/importer/:resourceId": {
		redirect: route[8].redirect,
		getData: route[8].getData,
		Component: route[8].default,
	},
	"/repositories/:repositoryId/devices/": {
		redirect: route[9].redirect,
		getData: route[9].getData,
		Component: route[9].default,
	},
	"/repositories/:repositoryId/devices/flat": {
		redirect: route[10].redirect,
		getData: route[10].getData,
		Component: route[10].default,
	},
	"/repositories/:repositoryId/nameComposition/": {
		redirect: route[11].redirect,
		getData: route[11].getData,
		Component: route[11].default,
	},
	"/repositories/:repositoryId/projects/:projectId": {
		redirect: route[12].redirect,
		getData: route[12].getData,
		Component: route[12].default,
	},
	"/repositories/:repositoryId/projects/": {
		redirect: route[13].redirect,
		getData: route[13].getData,
		Component: route[13].default,
	},
	"/repositories/:repositoryId/resources/:resourceId": {
		redirect: route[14].redirect,
		getData: route[14].getData,
		Component: route[14].default,
	},
	"/repositories/:repositoryId/resources/": {
		redirect: route[15].redirect,
		getData: route[15].getData,
		Component: route[15].default,
	},
	"/repositories/:repositoryId/samples/:sampleId": {
		redirect: route[16].redirect,
		getData: route[16].getData,
		Component: route[16].default,
	},
	"/repositories/:repositoryId/samples/": {
		redirect: route[17].redirect,
		getData: route[17].getData,
		Component: route[17].default,
	},
	"/repositories/:repositoryId": {
		redirect: route[18].redirect,
		getData: route[18].getData,
		Component: route[18].default,
	},
	"/repositories/:repositoryId/users/:userId": {
		redirect: route[19].redirect,
		getData: route[19].getData,
		Component: route[19].default,
	},
	"/repositories/": {
		redirect: route[20].redirect,
		getData: route[20].getData,
		Component: route[20].default,
	},
	"/repositories/settings": {
		redirect: route[21].redirect,
		getData: route[21].getData,
		Component: route[21].default,
	},
	"/repositories": {
		redirect: route[22].redirect,
		getData: route[22].getData,
		Component: route[22].default,
	},
};
