// @generated
// Generated by hendriksRouteGenerator.ts
export const routes = [
	"/",
	"/login",
	"/logout",
	"/register",
	"/repositories/:repositoryId/",
	"/repositories/:repositoryId/deviceDefinitions/",
	"/repositories/:repositoryId/devices/:deviceId/:deviceTimestamp",
	"/repositories/:repositoryId/devices/:deviceId/",
	"/repositories/:repositoryId/devices/:deviceId/importer/:resourceId",
	"/repositories/:repositoryId/devices/",
	"/repositories/:repositoryId/devices/flat",
	"/repositories/:repositoryId/nameComposition/",
	"/repositories/:repositoryId/projects/:projectId",
	"/repositories/:repositoryId/projects/",
	"/repositories/:repositoryId/resources/:resourceId",
	"/repositories/:repositoryId/resources/",
	"/repositories/:repositoryId/samples/:sampleId",
	"/repositories/:repositoryId/samples/",
	"/repositories/:repositoryId",
	"/repositories/:repositoryId/users/:userId",
	"/repositories/",
	"/repositories/settings",
	"/repositories",
] as const;

export type RouteDef = (typeof routes)[number];

export type RouterArgs =
	| ["/"]
	| ["/login"]
	| ["/logout"]
	| ["/register"]
	| ["/repositories/:repositoryId/", { repositoryId: string }]
	| ["/repositories/:repositoryId/deviceDefinitions/", { repositoryId: string }]
	| [
			"/repositories/:repositoryId/devices/:deviceId/:deviceTimestamp",
			{ repositoryId: string; deviceId: string; deviceTimestamp: string }
	  ]
	| ["/repositories/:repositoryId/devices/:deviceId/", { repositoryId: string; deviceId: string }]
	| [
			"/repositories/:repositoryId/devices/:deviceId/importer/:resourceId",
			{ repositoryId: string; deviceId: string; resourceId: string }
	  ]
	| ["/repositories/:repositoryId/devices/", { repositoryId: string }]
	| ["/repositories/:repositoryId/devices/flat", { repositoryId: string }]
	| ["/repositories/:repositoryId/nameComposition/", { repositoryId: string }]
	| ["/repositories/:repositoryId/projects/:projectId", { repositoryId: string; projectId: string }]
	| ["/repositories/:repositoryId/projects/", { repositoryId: string }]
	| [
			"/repositories/:repositoryId/resources/:resourceId",
			{ repositoryId: string; resourceId: string }
	  ]
	| ["/repositories/:repositoryId/resources/", { repositoryId: string }]
	| ["/repositories/:repositoryId/samples/:sampleId", { repositoryId: string; sampleId: string }]
	| ["/repositories/:repositoryId/samples/", { repositoryId: string }]
	| ["/repositories/:repositoryId", { repositoryId: string }]
	| ["/repositories/:repositoryId/users/:userId", { repositoryId: string; userId: string }]
	| ["/repositories/"]
	| ["/repositories/settings"]
	| ["/repositories"];
