import {
	ConnectablePidSymbol,
	type ConnectablePidSymbolProps,
	type PidPort,
} from "./ConnectablePidSymbol.tsx";
import { SymbolSvg, type PidSymbolProps } from "./SymbolSvg.tsx";

const ports = [
	{ id: "inlet", type: "target", side: "left", x: 0, y: 0.5 },
	{ id: "outlet", type: "source", side: "right", x: 1, y: 0.5 },
] satisfies readonly PidPort[];

export function PlateHeatExchangerSymbol(props: PidSymbolProps) {
	return (
		<SymbolSvg {...props} viewBox={[0, 0, 43.298, 46.416]}>
			<path
				fill="none"
				fillOpacity="1"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth="1.06299"
				d="M18.071 12.757h34.723V58.11H18.071z"
				transform="translate(-13.842 -12.225)"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M21.26 12.402v46.063"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M42.552 12.467V58.53"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M38.98 12.467V58.53"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M35.498 12.288v46.063"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M31.748 12.378V58.44"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M28.266 12.378V58.44"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M24.695 12.378V58.44"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M49.606 12.33v46.064"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M46.123 12.33v46.064"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M17.857 16.045h-3.66l-.09-.09"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M52.857 15.955h3.929"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M52.946 54.884h3.75"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M18.125 54.795h-3.929"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M14.196 14.17v3.571"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="m56.696 14.17.09 3.571"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M56.696 53.188v3.482"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M14.196 53.188v3.482"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="m18.125 15.955 34.732 38.929"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
			<path
				fill="#fff"
				fillOpacity="1"
				fillRule="nonzero"
				stroke="#000"
				strokeDasharray="none"
				strokeDashoffset="0"
				strokeLinecap="butt"
				strokeLinejoin="miter"
				strokeMiterlimit="4"
				strokeOpacity="1"
				strokeWidth=".708661"
				markerEnd="none"
				markerMid="none"
				markerStart="none"
				d="M52.768 15.866 18.036 54.795"
				color="#000"
				display="inline"
				overflow="visible"
				transform="translate(-13.842 -12.225)"
				visibility="visible"
			/>
		</SymbolSvg>
	);
}

export function ConnectablePlateHeatExchangerSymbol({
	nodeId,
	selected,
	orientation = 0,
	maximumSize,
	className,
}: ConnectablePidSymbolProps) {
	return (
		<ConnectablePidSymbol
			nodeId={nodeId}
			selected={selected}
			orientation={orientation}
			ports={ports}
		>
			<PlateHeatExchangerSymbol
				orientation={orientation}
				maximumSize={maximumSize}
				className={className}
			/>
		</ConnectablePidSymbol>
	);
}
